== The Life of John Davis

I was born at Amesbury, near Salisbury, Wiltshire, about the year 1667,
of honest parents, who gave me a moderate education, according to their circumstances;
and I can remember,
that so early as the eighth or ninth year of my age (being then more than
commonly inclined to evils and follies incident to youth,) how the Lord
followed me with his reproofs of that which I now know to be his Spirit.
In those days I was brought under such sorrow,
that I often washed my couch with tears for my _then_ offences against Him;
and more particularly about the fifteenth year of my age, when,
being visited with a sore sickness of nine months`' continuance,
which brought me near death,
I had the spirit of grace and supplication poured out upon me,
though I was not then sensible what it was that brought
me under such sorrow and repentance for my sins;
yet, I could truly say, with David,
"`I had watered my couch with my tears,`" which I often did: and am satisfied,
that had the Lord then taken me, I should have been in peace with Him.

About the sixteenth year of my age, I was made an apprentice by my uncle,
who proposed doing great things for me, which he probably would have performed,
had he lived; but he was taken off by sudden death, and so I was disappointed.
I then began to apply myself diligently to business,
endeavouring to give satisfaction to my master and mistress,
who were by profession Papists;
and with much trouble and difficulty I got through my time.
So great an impression did my illness, and the visitations of Divine Love,
make upon my spirit, that for some years after, I endeavoured to live in the fear of God,
and was often intent on matters of religion; insomuch,
that I began to be very uneasy under the profession I then was in,
(the Church of England,
so called,) thinking the professors of it too loose both in principle and practice;
and living, as I did, in a Roman Catholic family,
I occasionally had some discourse with a priest of that community,
with whom I was acquainted,
and who seemed to be more strict and religious than those of my own persuasion generally.
I was willing to ask counsel of God in a matter of
so great importance as the salvation of my soul,
which was the only inducement for which I was, at that time,
(according to my understanding,) honestly concerned.

Being in a strait in my mind, in this matter, after reading some books of dispute,
one night as I was going to bed,
it came into my heart to pray to the Lord in the few following words,
with more than usual fervency of spirit,--"`O Lord God! be pleased to show the
way in which I may worship you acceptably;`" which was all I had to say.
I took particular notice of this, and further conferred with the priest,
whom I looked upon as a good man.
I consented to go to confession with him,
thinking the Lord had answered my short prayer before mentioned,
and that now I was right.
He furnished me with books, and I soon became a zealous Papist,
though their foolish stories and legends did not work much upon me,
neither was I fond of many things which they did.
Some of them seemed too much bigoted, and I grew a great disputant,
thinking I was right and meritorious in gaining as many proselytes as I could.

But amidst all my zeal and performances, as I increased in years,
I increased in wickedness:
for now I began to poison my mind with reading plays and romances, and other bad books,
by which I was exposed to many temptations, and very often fell into them.
Then was I disappointed in the very end for which I changed my religion,
which was to get the victory over the many evils I found increasing in me;
and though I was more than commonly zealous in going to confession,
and receiving the sacrament, yet, I still returned,
"`like the dog to his vomit,`" not being benefited by these lifeless performances.
Early would I walk alone in the porch, or fields,
often breathing out my soul to the Lord for pardon and help,
against the flood of iniquity I saw pouring in upon me.
All did not help me to overcome,
though I am now satisfied the Lord had regard to the sincerity of my heart, at that time,
which was wrought by his Grace and good Spirit.
I now can remember the difference there was in my prayers,
being sometimes under much tenderness of spirit, and at others, barren and formal:
and this I now know to be the work of God, though I then knew it not.
I mention the circumstance,
to set forth the love of God to that seed of sincerity and truth, which the Lord,
in love and mercy, sows in the hearts of the children of men,
to which I desire they would all have regard,
minding the operation of it under the lowest dispensation;
for in so doing they will have comfort, and be brought into remembrance before God,
who delights to do good to the children of men.

Now, finding all my praying, fasting, confessions, zealous performances,
and whatever I could do,
ineffectual to the gaining of the victory over the corruptions of my heart,
I grew weary of them, and began to conclude that it was impossible to attain it,
and that I knew enough of religion to no purpose.
I then hearkened to Satan, who told me secretly in my heart,
that I might do something when I was old; but at this time of my life,
these things were impossible; and if I did but go to confession before I died,
all would be well.
I believed him,
and gave myself liberty then to follow the devices and desires of my heart:
a willing servant I became to Satan, following him almost wherever he led me.
I then began to see that some of the priests were knaves and cheats,
and far from what I once thought them to be; so I despised both them and their religion,
and became a libertine.
In this manner I took off my religion at once,
reserving to myself the intention of going to confession before I died,
though I had a very mean opinion of that forgiveness;
but I so quieted my mind for the present.
Yet the Lord followed me by his reproofs and terrors in my conscience,
and I was many times condemned for wickedness.
I got to my drink, company, and cards again, and many other ways did I find,
to stifle this faithful and true witness of God in my heart; yet,
the Lord still found me out--there was no hiding from Him.
No rest had I for many years--no place easy to me;
my very delights were made bitter to me, and I could truly say,
"`There is no peace to the wicked;`" for wherever I went,
sorrow and trouble were my portion.

I served out my time, and soon after married a sober honest woman;
but before I had been married two years, many troubles, disappointments,
and losses were our portion; all this was but the beginning of sorrows.
Next we took a house, and entered into business.
In a few years, through continual disappointments and losses,
we were obliged to give it up, not having enough left to pay our creditors,
by about forty pounds.^
footnote:[In the sequel it will be seen,
he afterwards discharged this on the principle of strict justice;
and in a striking manner.]
I was thus driven from my wife and children,
and forced to seek my bread in a foreign land,
where I was reduced to live without bread for days together;
and to many other hardships was I brought, having neither money, business, nor friend.
This was a time of great distress to me, who had till then lived in great fulness;
and it was by the good hand of Providence I was preserved
from being forced into the military service,
of which I was in great danger several times.

At length I found means to return to England;
and after begging my way for nearly two hundred miles, I came into the North,
where my wife was with her relations, who used her but indifferently,
by reason of our misfortunes; consequently she was not in a capacity to help me much.
After staying sometime with her, bewailing our trouble, we again parted.
I went northward to seek for business, but was forced to spend all the little I had,
before anything fell to my lot.
Having now neither money, business, nor friends,
I thought to become a soldier to earn my bread; and though I was actually enlisted,
yet by the good hand of Providence I got of, and entered into a pretty good trade;
and shortly I was enabled to help my wife and children.
This lasted not long, for I was once more brought into great straits, and many hazards,
even of my life, through temptations: yet,
I was not forsaken by the good Hand that so often preserved me.
My religion had not taken deep root, for amidst all my trials I was very wicked,
and had no power to reform those evil inclinations that had such power over me.

After some time, I again got into profitable business; my wife and children came to me,
and it seemed as if Providence grew kinder towards us; but then on a sudden,
in a few months, we lost three children, being all we had;
and my wife was nearly following them, by reason of great sorrow.
Notwithstanding my heavy afflictions, the strength of Satan was such,
I seemed bound to serve him still, almost wherever he led me; only,
amidst some great temptations, a secret Hand preserved me when I knew it not,
for the enemy sought even the destruction of my outward life:--four instances
of which I shall mention when rebelling against the convictions of my own heart.

The first was my going into a water, which proved so deep,
that all who saw me wallowing in it expected I should be drowned;
but my life was saved by the courage of a countryman,
who leaped into the pool in his clothes (he being a swimmer, which I was not),
and came just in time to save my life.
He used care in getting the water quickly out of my body; but,
though successful in his endeavour, a fever and the measles were brought on;
so that I was in great danger of death; but in time I recovered my health.

Another instance:--As I was walking in the street one dark night,
having only a cane in my hand, two persons, called gentlemen, being drunk,
supposed me to be a person who had attempted to rob them.
They came upon me with their swords drawn in their hands, threatening to kill me;
but I stepping aside a little, they missed their first opportunity;
and that little space being given, I had time to undeceive them, and so escaped.

Next was, (being intoxicated) I got a fall from a horse,
which threw me into the road in the dark; by this I broke a bone,
and lost the use of my right ear from a bruise on my head.
Being insensible, there I had lain till lost,
had not a countryman coming along stumbled upon me.
He caused me to be carried to a house, where I lay several hours before I came to myself.

Next was, by another fall from my horse in the dark, when again intoxicated;
from which I was so hurt in my head,
that I was taken up insensible from among several horses; so that, had not the same Hand,
in this, as well as in all the other accidents, preserved me, I must have been lost.

When I considered these preservations, and how many of my acquaintance,
with some of my companions, were cut off in the midst of their wickedness,
it brought great terror on my mind, and a fear possessed my heart that I should be next.
And one of my companions, having, by excess in drinking and otherwise,
brought on a distemper, in his young years, which ended his days, I,
with many others of my old companions, went to see him laid in the ground.
We stayed some time looking into his grave,
and it arose fresh in my heart,--"`If you are the next, how are you prepared?`"
This, though it made me solid and considerate for awhile, yet,
going again with my companions, and drinking, these thoughts soon went out of my mind.
I got very drunk, had several falls from my horse, and that which I last mentioned,
happened this very night, and cost me at least ten days`' sickness;
during which I had time to consider of several things,
and I formed many good resolutions; but, when company and temptations presented,
they were all lost; and I was carried on by the fury of Satan,
and the strength of my own inclinations, to be still more and more wicked,
rapidly filling up my measure of iniquity;--and the
chain by which I was bound seemed stronger and stronger.

Notwithstanding all this, so great was the love and mercy of God to me,
that He followed me by His reproofs in my heart, although I then knew not what they were.
By terrors and condemnation in my conscience, I had no rest;
for fear possessed my heart many times; yet,
so hard--so dark was it--that until the Lord was pleased to touch it effectually,
and to look on me with tender compassion, I could not return.
But now, blessed be His holy name, the time drew near when He was about to arise,
to make bare His arm; to execute His vengeance on my soul`'s enemies,
and bring me to judgment--"`to open the prison doors,
and to let the oppressed go free;`"--which was effected in the following manner,
and for which my soul at this, as well as at many other times, bends in deep humility;
and, in bowedness of spirit, I return Him the praise, who only is worthy forever.

Now, I shall give some account of the way and manner by
which the Lord began to work a reformation in me,
to plead with me for my rebellion, and to set my sins in order before me,
which brought that godly sorrow upon my heart that gives true repentance,
never to be repented of.

In 1702, about the thirty-sixth year of my age, I then being servant to a great man,
in a family which consisted of about one hundred and twenty persons,
I had contracted a particular friendship with a young man,
who was almost as wicked as myself,
with whom I was frequently practising some extraordinary excesses in drinking, gaming,
and many other ways of wickedness, even to the endangering of both soul and body.

The Lord, who had seen the fury of Satan,
that was hurrying me into the pit of destruction, began to arise,
to be avenged of his adversary, and of that nature that had joined with him.
First, He laid his hand of judgment on my companion,
who was taken suddenly with violent convulsions,
so that for several hours his life was despaired of.
I was then actually playing at dice among my companions, when word was brought me,
that he was dying.
I soon left my game and went to him,
which event I seldom remember without being bowed in spirit,
in much thankful acknowledgments to the Lord,
for His great mercy to so unworthy a wretch as I then was;
and I am made to say many times, "`Surely, if the Lord had not helped us,
we had been as Sodom, and been made like unto Gomorrah.`"
But for His seed`'s sake, which He still loved,
that was oppressed and loaded as a cart with sheaves, He was pleased to look upon us,
when we lay polluted in our blood, and said to us,
_"`Live:`"_ for which my soul cannot but adore his goodness and mercy,
and make humble acknowledgments at this time, returning Him all the praise,
who only is worthy forever.

Now to proceed, I was surprised to find my friend struggling as it were with death,
and I sat me down on the bed on which he lay.
After using medical means,
he continued in this precarious situation for a considerable part of the
night.--The consideration of his future state took hold of my mind,
and I said in my heart, "`If he go now,
eternal misery must be his portion;`" and turning the reflection home to myself,
that fear, horror, and amazement seized me, which cannot be truly described by words.
This settled upon my spirit, from under which I was not able to get;
for the Lord broke in upon me, and deep was my distress of soul at this time:
it is hard to tell my thoughts then, which were accompanied with tears without words;
and I had that night an alarming sight of the miserable state my poor soul was in.
I saw that I was got as it were to the brink of the pit,--that
my measure of iniquity was nearly filled up,--that if I went on,
everlasting wrath and condemnation from God would be my portion;
and I did not know how soon.
Those that have in measure witnessed such feelings, may guess at my condition,
but none else can.

Towards the morning of the blessed day, (I call it so because the Lord made it so to me,
by His eminent visitation, for which I am thankful) I was still more surprised,
when my companion, who was somewhat recovered of his convulsions,
preached such a sermon as I never before heard.
O! how did he exclaim against the pleasures, follies, and vanities of this world,
condemning those that lived in and loved them;
continuing his discourse nearly an hour pretty regularly,
and in a strain so affectingly reaching, and attended with such power,
that both myself and a young man who sat up with me, were much broken in our spirits,
and ready, like some of old, to query, "`What is the meaning of these things,
which are so strange to us?`"
He being after a time still, I asked him a question;
but he answered not--he was insensible; and so continued for nearly twenty-four hours.
The young man who sat up with me was much tendered;
and when my fellow servant came to himself, I asked him several questions,
but found he knew nothing that had happened to him all that time;
which caused much wonder in me.
I went to bed, in order to get some rest after such fatigue, and then to my friend again.
I found him much down in mind; and what had happened made such an impression,
that we came to the conclusion,
that the amendment of our lives was highly and absolutely necessary:
but how to put it in practice we knew not,
being both of us destitute of so much as a profession of religion; only for form`'s sake,
and to please men, we sometimes went to a chapel that was in the house.

On this great affair we began to consult what methods
to take to put those good resolutions into practice;
we sought to obtain a state of righteousness by walking in the way which led to it,
to the best of our knowledge; we looked into the Scriptures;
enquired concerning the principles and doctrines of religion,--and
the Holy One of Israel who thus led us to seek Him,
did soon perform his promise, in helping us to find Him,
who is "`the Author and Finisher of the faith of all who truly believe in Him.`"
The family doctor (Heathcote) was with us about that time; he was a Quaker by profession,
and one of whom we had taken much notice.
His conduct was sober and pure, and we thought him too full of self-righteousness,
because he would speak of the peace and satisfaction he felt,
and would recommend us to wait upon the Lord in stillness
for wisdom and counsel in our own hearts.
This was such a mystery to us, that we believed nothing of it; but the Lord,
who regarded us, furnished him with suitable answers to all our subtle questions.
I could not but think, if what he spoke of was true,
(as to his inward feelings,) he was the happiest man living;
but could not believe any such state attainable on this side the grave.

Nothing, or very little, did I then know of the Quakers`' principles.
I thought them a foolish, mistaken people, and rather despised than hated them.
Now the Lord, who would do us good, condescended in his love to undeceive us,
as to the doctor, in the following manner:--I had brought occasionally into our company,
a man who, I thought, was able to puzzle him,
who asked him this question,--"`Do you believe, if you should die within a few minutes,
you should be saved?`"
The doctor, considering it a very serious query, and having a glass of wine in his hand,
leaned back in his chair for some minutes, quite silent.
I felt much concerned in that question, and was ready to eat (as it were) the words,
before they came out of his mouth, in reply.
Sitting uprightly again, he looked solidly, and cheerfully answered,
"`If this wine in the glass were poison, and I were to die with taking it,
(unadvisedly,) I feel satisfied in my mind,
that the Lord would receive me in his mercy;`"--(or to this effect.) As yet,
I have had an "`if`" in my mind, and I said to myself, "`_if_ this be true,
and such a state could be attained by me, it is worth the world and all things in it.`"

Now, although our past sins were become such a burden--greater than we could bear--yet,
the thought of turning Quaker was so terrible,
that we concluded to have nothing to do with it, but try to find out some other way,
whereby we might obtain pardon for our sins, and get peace with God.
It happened that this doctor had found in our master`'s library,
Robert Barclay`'s [.book-title]#Apology,# which he lent me to read;
and when I had perused but a part of it, my understanding was so fully opened,
as to the doctrinal part of Friends`' principles, that,
from that time to the present day, I have never had a doubt concerning their truth;
and my friend was of the same opinion; but it brought us into a great strait.
We saw they were right, but the way appeared so narrow,
that as yet we could not think of so much as even attempting to walk in it.

I cannot easily describe the reasonings and consultings on this occasion;
when the enemy would represent,--"`You must be stripped of your pleasures and delights,
all your friends and companions, and everything that is lovely in your eyes,
and become the mock and scorn of all that know you!`"
The promising circumstances I was in, as to outward things,
and the strong inclination to evil, made me conclude at times,
if there be no other way for me to be saved, I must perish,
for it was impossible for me to join with this.
But, when I thought of peace with God, and the enjoyment of a quiet conscience,
I was much perplexed in my mind, still striving to save myself from being a Quaker.
My friend was under much the same circumstances; but God,
whose eyes run to and fro in the earth, beholding the evil and the good in all mankind,
saw our weakness, and the strength of our enemies.
He arose for our help, and we saw wonders;
and were made witnesses of part of the prophecy of Joel,
spoken of in the second chapter of the Acts, 17th verse, "`And it shall come to pass,
etc.`"
I having many significant dreams, and my friend seeing several strange visions,
which we imparted to each other to our great amazement;
at which our doctor appeared much pleased, who still recommended us to wait on the Lord,
in stillness, for his grace to move in our hearts, for our instruction.

Here I would tenderly caution all Friends who read these lines, to be very careful,
and keep their places in the Truth,
when their lots may be cast among those who are tender in spirit, or newly convinced;
for had not this doctor been preserved in tenderness, during his acquaintance with us,
it might have been to our great hurt;
for there was a part in us that waited for his halting,
and there was scarcely a word or motion of his we did not observe.
But he being kept solid and weighty in his spirit, was made helpful to us;
and it was a time of great comfort to him for our sakes,
through the kindness and love of God to us all;
for which my soul is thankful in the remembrance of that day of great love and mercy,
and I desire that God alone may have all the glory, who only is worthy, says my soul!

It being thus with us, and extraordinary things working much on our minds,
with many Scriptures opening clear to our understandings,
for our comfort and encouragement,
we were a little strengthened in our resolutions
to leave all and follow the Lord in His own way;
and I was very sincere and earnest in the work.
My nights were often spent in waiting on the Lord in stillness and quietness of mind,
which the Lord was often pleased to give me,
frequently bringing to my remembrance my former experience;
so that I witnessed the truth of that saying of Christ, "`When the Comforter does come,
he shall bring all things to your remembrance, whatever I have said unto you.`"
Thus I was made sensible of His kindness, in visiting me even in my childhood.
These things were clearly brought to the view of my understanding;
and in my waitings on the Lord,
times and places were set before me when and where iniquity prevailed,
as if it had been but yesterday.
Moreover,
the Lord showed me His many deliverances from particular
temptations into which I had fallen,
and which endangered my life;
and thus I saw His preserving providence had been around me through all,
and that He now offered to cancel the black scroll
of iniquity which was written against me.
I further saw,
that it was He that had begot that short prayer in my heart (before mentioned:) and now,
after sixteen years, had come to show me the way in which I might worship him acceptably,
if I would accept it; but it must be on His conditions, not my own.
He bid me not fear,
and that He would help me,--that all things (however impossible
in the eyes of men) were possible with Him.

Thus the Lord reasoned with me, gave me understanding,
and won upon my spirit by His great love and condescension,
so that a desire was begot in my heart to follow Him; and for a trial of my obedience,
He gave me this word, which lives on my spirit,--"`Cease to do evil.`"
Under this exercise, I was as one dumb before Him, who opened my heart to say, "`Lord,
you have bid me '`cease to do evil;`' how can that be?
You know all my former resolutions come to nothing, and I am as dust before you,
wherein is no strength.
Oh! do manifest your power, that my soul may be obedient to your will.`"
After this supplication in soul, I was still awhile,
when on a sudden I became as one in a trance,
and my spirit was carried into a place that was very glorious,
where a voice of praising God was heard.
I was willing to have stayed there; but after some time, returning in my spirit,
I heard a voice saying, "`This is the power that overcomes the world,
which those that follow me truly shall enjoy, and be clothed in it.`"

None but sensible souls can understand how I was affected
with this great condescension of the Great Everlasting God,
to so wretched a creature as I then was, for I was in great distress;
but God finds a way to help such: in confidence of which, my heart was open to say,
"`O Lord! for a token of your faithfulness, and that you will be with me, help me,
and give me victory over this evil;`"--meaning that
which had the greatest place in my heart.

Now what shall I say to extol the mercy and wonderful love of God!
For many months after, I could not accuse myself in thought, word, or deed,
in that particular evil.
And I stand this day a witness for God,
that He is both able and willing to save men from sin.
At this time I am made to testify, in His fear,
that it was by a measure of the same light and grace which reproved me for my sins,
that my understanding was opened, and that I came to witness what I have before written.
By the power therein, my soul came to know an overcoming, that is of God and not of man;
although it be man`'s accepting and using it during his visitation.

The Lord having thus won me to willingness in some degree,
was pleased to teach me how to wait upon Him for strength; which, from time to time,
He afforded, and now began to kindle the fire of His judgments in my heart,
against that seed of iniquity which was in it.
I was made willing to endure the burning thereof,
and I came to understand that great sight which Moses saw,--the "`bush burning
and not consumed;`" for although it was hot and painful in my heart,
yet the cool breath of the love of God, at times felt,
made me willing to endure with patience: having hope,
that thereby He would cleanse my soul; and, in His own time,
therein prepare a habitation for his Holy Spirit.
This was what I earnestly desired, and a travail was often on my spirit,
that His holy fear might be placed on my heart; so in the strength given me,
I went about my outward business, in which the Lord concerned me to be more careful,
honest, and diligent than I had been;
and I was helped to bear a good testimony for the Truth in that respect,
to which my enemies were made to confess, to the glory of His name that did it.

Now to return to my friend, whose distemper turned to asthma,
for which no doctor or medicine were sufficient.
The Lord having worked much with him showing him what He required, yet,
he could not give up to the hard condition of being a Quaker.
But, as he was sitting alone in his room, the Lord opened in his mind,
that if he would but be obedient, he should be cured without doctor or medicine;
upon which, he left off making use of either; and, striving to be faithful,
in about two weeks he was able to go out of his room, when, in the power of God,
he declared many excellent things concerning Him and His kingdom,
in the hearing of myself and of several others of the family,
who seemed pleased with his company.
Thus we began to be taken notice of; and there were some Nicodemuses,
who would steal to us often in the night;
for it was a time of large visitation over the family, insomuch,
that not less than seven or eight persons therein were convinced of Truth`'s principles.
For my part, I was made to leave all company but this,
and often to retire in the fields and gardens,
pouring out my prayers and tears before the Lord,
for mercy and strength to go forward in the way my feet were set;
for the enemy raised up much persecution, temptation, and provocation against me.

My old companions urged me to go with them to former practices,
having a pleasure in my good company as they called it; for I could drink, game, sing,
and tell an abundance of diverting stories; but I dared not go,
and would sometimes lock myself up, and occasionally steal into the garden or fields.
Once they found me, and with them, they said, I must and should go.
So, after reasoning awhile,
I consented on condition that I might have my liberty to drink only what I pleased,
and not meddle with any games.
To this they consented, and I went, staying several hours;
but I was concerned to keep near the Lord in spirit, who preserved me,
so that I drank very little, and talked less;
and I could perceive they got tired of my company, I being a burdensome stone to them.
I left them, and they never asked me to go with them again, that I remember.

Being got over this, I became zealous for God, conversing with the priests,
(of whom many frequented the family,
there being several professions to religion in the house,)
but the Lord gave me dominion over their spirits,
and wisdom was in my mouth to confound their deceit.
One more wicked than the rest, undertook to preach against the Light within,
and had leave from our master to use the chapel for that end.
Great expectation was in many, to hear what he would say; but the Lord so confounded him,
that he got into great disgrace and disrespect, insomuch,
that many of the family were ashamed before me of his mismanagement.
I got to a place where I heard part of his discourse,
which confirmed me of the wickedness of his act,
and gave me a good opportunity to lay open the vileness
of his spirit before some of the family who were tender.
I was further concerned to expose the spirit of pride, the dressing of the women;
and to cry out against the steward`'s injustice and unmerciful dealing--against gaming,
singing, and drinking.
And I would sometimes sit down, and warn them for their good,
as the Lord opened my understanding.
Truth having dominion over all, they would be sober and pleased with my discourse;
and the Lord was with me, and encouraged me.
Many of the family believed this fit (as they called it) would not last long,
believing I had more wit than be a Quaker; and I had never yet been at a Meeting.
The doctor was gone, and my friend and I left alone among a perverse people,
who looked on us as speckled birds; and though such as were tender among them, loved us,
they had not courage enough to own us.

Shortly I was concerned to go to a Friends`' Meeting, about five miles off; and,
notwithstanding what had passed,
I had much ado to persuade myself to sit down among such a poor despised people:
but the Lord led me.
We sat in silence nearly two hours, and I had a testimony in my heart for them,
that they were of God;--He owned them, and I was glad I was among them,
for the Lord`'s power and presence was with them, of which I was a witness.
There was a woman Friend who spoke a few words, by which my spirit was comforted.
Meeting broke up, several perceiving I was a stranger, were civil to me;
and an ancient honest Friend took me to his house.
After spending some time together in sweet conversation, we parted.
This Friend was made instrumental as a help to me in many respects.

I rode home, but the news of my having been at a Quakers`' Meeting got there before me;
and a mighty noise it made.
I took little notice, but went to my friend,
to inform him of the satisfaction I had had that day,
and to encourage him to faithfulness.
He was now well enough to leave his room,
and I was earnest with him to be careful of drinking, for that was his danger.
He did not follow my advice; for the first day he went out of his room,
after many weeks`' illness, he unguardedly took too much drink: and in the afternoon,
the Lord struck him again with a convulsion fit,
which held him about an hour with such violence,
that it was generally thought he would not recover; which mightily alarmed the family.
I had a sense of his disobedience, but had hopes in the Lord`'s mercy for him.
After some time he recovered his reason, though his distemper held him several days.
When he was well, (sad to relate!) he followed his old habits of disobedience,
which became my great burden, insomuch,
that I was often bowed down before the Lord to strengthen him;
I following him up and down the house; and when he was with his unprofitable companions,
I would go and give him a look.
The terrors of the Lord would seize him, so that he would leave them and come to me,
and I had much mental exercise on his account.

He desired to go to a Meeting with me, but he daily grew more and more wicked,
and became worse than ever I knew him; so that I was afraid he would be finally lost,
for I was not then so much acquainted with the depth
of the great Fountain of love and mercy,
as I hope I have since been.

About this period, one of our "`Lady`'s maids`" manifested a tenderness of spirit, and,
showed herself desirous of upholding the Truth in its inward and spiritual appearance,
and grew uneasy respecting her dress.
This raised great persecution against me,
and much displeasure from the "`Lady`" who called the priest to her assistance,
when they two endeavoured many ways to get me out of the family.
They told my master I was a Jesuit, that I would corrupt the whole house,
and it was scandalous in him to keep me.
Another thing which she was highly offended with
me was:--She attended the coronation of Queen Anne,
and being of a comely person, had the vanity to be dressed up in her court robes,
and appoint a time for the family and several neighbours to come and see her.
I was solicited among the rest thus to gratify her vanity;
but through the strength God gave, I was enabled to refuse,
and bear my testimony against the display;--calling it "`pride and vanity.`"
This made her very bitter at first, but she afterwards publicly declared at her table,
that she understood I had turned Quaker; and if true, it was for the better,
for now I served the family abundantly more faithfully than before.

The office I held I filled with satisfaction to my master,
so that he was not willing to part with me.
I began to be weary of the troubles I had long experienced in this family; yet,
in waiting on the Lord for direction,
he showed me I must remain until turned out of doors.
This counsel I was helped to follow.
My master was continually teased by his wife and the priest concerning me,
so that he sent for one of his stewards,--my particular
friend,--telling him I was not fit to stay in the house,
and therefore he must give me warning to quit.
The steward replied, "`the fit of humour he is in, will not last;
he has more wit than to continue in it.`"
My master, who liked me well, agreed to retain me on certain conditions,
which he desired the steward to propose, as follows:

[.numbered-group]
====

[.numbered]
_First._--I must engage not to go to the Quakers`' Meeting,
oftener than I used to attend Chapel, which was very seldom.

[.numbered]
_Secondly._--I must not talk of religion to the other servants,
or any of the strangers who came to the house.

[.numbered]
_Thirdly._--I must neither ask to go myself,
nor take any of the servants with me to Meeting.

[.numbered]
To the first I answered,--I know not how it may be if I stay twelve months here,
or if left at my liberty.

[.numbered]
To the second,--That I did not and should not _force_
any discourse of a religious nature upon any;
but if asked questions, I should consider myself at liberty to answer as I thought fit.

[.numbered]
To the third.--I could not tell whether I might or might not request any to go to Meeting.
If they had a mind to go I should not hinder them,
nor be compelled to refuse them my company, if I thought right.

====

He reasoned with me respecting my answers.
I being fixed, left him to carry them to my master.

About this time, as I was waiting on the Lord in my bed,
I had a view given me of having to meet much trouble;
and a cry arose in my heart to the Lord,
that He would be pleased to convince my wife of the blessed Truth,
so that I might have some comfort in that respect.--(She was then in London,
and I about eighty miles distant.) Such was the mercy and condescension of the Lord,
that before I saw her she was powerfully visited by Him,
and had become a religious character, and an honest Friend;
for which my soul makes thankful acknowledgment.

But to return to my friend, of whom I might write many things hard to be believed,
for which reason I shall omit them, and relate what follows:

The time drew near, when the terrors and judgments of the Lord followed him,
and he was brought in some degree to obedience; but the "`Lady,`" who was kind to him,
used all possible means to divert his attention from the right thing,
she having her instruments, who kept him almost continually intoxicated,
so that wickedness increased in him; and my trouble on his account was inexpressible.
One night, as I lay in bed, I had a sight of his further backsliding,
which brought great trouble on my spirit; and calling to a servant that lay near,
I bid him tell my friend I was not well, and I wanted to speak with him.
He got out of bed, and came and sat down by me,
when I told him the oppression of my spirit on his account,
and that the Lord was displeased with him; but for a time his heart was very hard.
I felt a cry within me to the Lord on his behalf, that He would touch his heart,
and make him sensible of the condition he was in; which I felt so forcibly,
that I could not forbear giving utterance to my secret feelings,
which was not usual with me.
The Lord, whose love is everlasting, answered my petition,
so that in a few moments this young man was humbled; and coming into my bed,
confessing and bemoaning his great disobedience, he told me,
that while that woman (meaning the "`Lady`") was his friend, he could not be faithful.
I advised him to break the chain, and go to Meetings, though she would be his enemy;
which he promised he would next First-day; but I was fearful he would break his word,
which he did.
For some time I watched him closely, to prevent his drinking to excess.

At the time of his coming into my bed, a report was raised in the family,
that the devil had appeared to me, and that I sent for my friend to allay him;
but this idle tale affected us not.
One First-day I got horses to carry us to Meeting.
The alarm being given in the family, a priest came from our master with a message,
commanding my friend to come to Chapel.
I undertook to answer the priest,
bidding him tell our master that when he (the priest)
proved himself a true minister of Christ,
we would come to hear him.
So away went the priest, and there soon came another messenger with the same command.
The chief servant beset my companion, telling him he would be turned out of doors;
but as for me, they thought me half mad, and cared little what became of me.
I greatly feared for my friend, who was weak.
At length I ceased to persuade him, and retired into my room to wait upon the Lord;
and I soon found a cry in my heart for his help, believing the Lord would strengthen him.
Finding him still in the hands of his false friends,
and the servant waiting for an answer to carry to the master,
I looked earnestly at my companion, and asked if he would go with me?
when he quietly gave answer for the master, that he had a friend to see abroad,
whom he would not disappoint for a thousand pounds of his master`'s money.
This was as marrow to my bones, and away we went;
but he cast a longing look behind at the palace of Egypt.
I encouraged him, by saying it would be the best work we ever did in our lives.
We got to Meeting, which was silent, excepting that a woman Friend spoke a few words;
and the Lord`'s power and presence was with his people,
of which we were measurably made partakers.
An ancient Friend took us to his house, encouraged us to be faithful;
and in much love we parted.

On going home,
we received information that our master had ordered
that we should not stay in the house that night,
but go to the inn near; and in the morning come to settle accounts, and be discharged.
The Lord gave me a good night, and we were both surprisingly strong next day,
when we went to arrange our matters, and to be discharged.
My friend was again sorely beset by the "`Lady,`" who wrought
many arguments to persuade him to resist his intended resolution:
and great fear I was in, on his account.
I had recourse to the Lord, by retiring to wait upon Him,
who was again pleased to give strength, so that he got loose.

Having paid our reckonings at the inn, we purposed going to London:
but next day the "`Lady`" sent for my friend to dispute
with a priest she had procured for the purpose.
Finding him so much inclined I advised him against it, but he would not hear me.
He promised soon to come back, and attend to a little business we had in view.
In this dispute my friend was much too hard for the priest.
Not being very well in bodily health, the "`Lady`'s`" dram bottle was fetched,
of which he unwarily partook.
Being thus entrapped, she took care to have him stay for dinner;
and after he had been plied with liquor,
till quite intoxicated (for which I was in much anguish), he came to me.
I was willing even in that plight, to take him on our intended journey (about ten miles),
hoping the ride might sober him; but, after some fatigue,
and reaching our place of call at night, I found him worse instead of better,
and was obliged to retire to rest,
leaving him in the hands of some of Satan`'s instruments, whom he met with there.
After the lapse of several hours, he became so entirely helpless with drink,
that I was under the necessity of leaving my bed to undress him, and next morning,
his evil companions being ready for him; to drinking they again went.
I waited awhile, but at length was obliged to leave him behind,
promising to see him again shortly.
On my return next day, I learnt that he had gone homewards in the usual plight;
and that the "`Lady`" was going from home,
and would not miss so good an opportunity of taking him away from me.
She therefore ordered a horse for him, and he went with her in this deplorable condition.
I followed, and found that he had gone,
leaving word of his intention of being back next First-day,
in order that he might accompany me to London; but I much doubted his word.
I cannot express the depth of my sorrow on his behalf, for he was very dear to me;
and the separation was like dividing a man from himself.
Such was my concern, for I felt that the forbearing love of God was, at that time,
very great towards his soul.

I found myself alone in the family where I had been very much respected;
but where they had now all become my enemies,
treating me in the most scornful and despicable manner--even
those whom I had particularly obliged;
which gave me a very low opinion of the friendship of the world:
and I had fainted if the Lord had not helped me.
When First-day arrived, to save horse-hire, I walked to Meeting.
While sitting there, I was so overcome with anguish of heart on my friend`'s account,
that I was soon obliged to leave.
I sent for the ancient Friend before-mentioned, to come out,
and told him that I believed I must once more go and try to find my poor friend.
He said he thought it was my proper duty; and I, being a stranger,
he helped me to procure a horse, upon which I rode twenty miles in much agony of spirit.
Reaching the place where he was, I put up hard by at an inn, and sent for him.
He returned for answer, that he would be with me soon:
but the "`Lady`" hearing I was come, made him promise not to see me;
so after waiting till a late hour, I went to bed, carrying my burden with me.
I had little or no sleep.
Next morning my friend sent me word the reason why he could not see me:
upon which I wrote him a few lines, and found my exercise removed.
I came away quite easy in my mind, and went home,
feeling great satisfaction that the Lord had empowered
me to perform that which was required at my hands.

I then prepared for my journey to London, intending to go as soon as possible.
Meeting with a Friend going there, I bought a horse, and set forward with him,
after selling, for a considerable sum, all my superfluous apparel,
intending never more to wear it.

I may here repeat,
that I had to endure much trouble and exercise of spirit for months together,
while an inmate of this great family; but through all,
the Lord marvellously upheld and kept me in my proper place,
so long as I was obedient to His holy law in my heart,
enabling me to bear testimony to His Truth;
and in due time I felt freedom to quit my situation, though worth sixty pounds a year.
For these mercies, my soul`'s desire is to magnify His grace,
and give Him all the praise, who alone is worthy forever.

I would here observe, that among those of this establishment who were visited,
and whose understandings were measurably opened concerning Truth`'s principles,
but who proved rebellious thereto, one was drowned while wading through a river.
This individual had turned into bitterness against all Truth and Friends;
and the accident occurred in about a year after I had left the family.
Another, who clearly saw what was required of him, but not yielding obedience,
attempted to cut his own throat.
Being prevented, he found means to hang himself.
One of the messengers before named,
who brought the order for my friend not to go to Meeting, but to Chapel,
fell from a chair in a state of intoxication, and died in a few days.
Another fell down some steps going into a room we
used to call "`hell,`" whereby he was killed.
And the Lady`'s maid, before alluded to, was turned out of her place,
for her abominable pride and ill carriage; and she came to nothing.

I would tenderly advise all who may read this,
and who may be under a visitation from God, to be very careful not to slight His mercy,
for He is thereby provoked to withdraw His favour and protection;
and when any poor creature loses this, woe and misery will be his portion.
The Lord is, far beyond expression or comprehension, merciful; but He is, likewise,
just and righteous; and when He executes His judgments on the wicked,
and those who will have none of His counsel, but who set at nought all His reproofs,
choosing not the fear of Him;--these expose themselves to
the calamities spoken of in the first chapter of Proverbs.
Alas! it is much to be feared,
that some of the persons above alluded to might be of this number.
In the consideration of which, my soul is much bowed in remembrance of His mercy to me,
and that I was made willing and obedient to Him in the day of my visitation,
when I was far from His fear.

But to return.--Being on the road to London, with the Friend before-named,
and differing from him in outward appearance, he, for some time, was shut up in his mind,
not knowing what sort of companion he had got,
and was ready to conclude that I scarcely came into the fold at the right door.
But before we parted, the Lord gave us a taste of His love together,
whereby we were visited in our respective measures; and though I was a babe just born,
I was begotten of the true Seed; and this reminds me of an event which occurred.
Having a love to honest Friends, we inclined to stop all night with a certain individual,
who resided about ten miles off, and got horses accordingly;
but when we arrived at his house, we found him so shut up in his mind toward us,
that we had not freedom to remain; so we returned in the dark.
In external appearance we seemed more like wolves than sheep.
Although this Friend had heard of us, yet, being rich, and living in a by-place,
he was struck with fear that our object in visiting him was plunder.
He soon after saw his error, and came after us; but we were gone.
Reflecting on this circumstance, the Lord taught us not to place our dependence on man,
but to look unto Him.
And I have thought how good it is, for all who profess to be followers of Jesus,
to stand in His counsel; and when they meet with tender-spirited ones,
not to judge entirely by the outward appearance,
but to let pure wisdom ever be our guide,
so that we may be enabled to judge righteous judgment.

Another matter happened on the road near London, which I shall mention:
Some Friends going to Meeting, who were known to my companion, stopped to speak to him.
I being a short distance behind looked towards them,
and felt a spring of life dart into my heart, as sharpened by the sight of them,
which made me thankful the Lord had brought me among
a people whose unity stood in the life and power.
One of these Friends wore a short plaited cravat, at which I felt offended,
and resolved in my mind, that whatever happened, I would never wear such a thing as that.

We reached London, and were kindly welcomed by my wife,
who had become a plain honest Friend:
and I also felt constrained to appear in my clothing more like one of that people.
I resolved however to imitate only the smartest I had noticed among them,
and by no means to wear a cravat.
I parted with my long wig, and bought a short one; bought cloth for a suit,
and carried it to a Friend to make up,
who wished me to give directions how the suit was to be made.
I told him I had not freedom, but (he being an honest Friend) would leave it with him.
He made the clothes so plain, I was much ashamed to put them on.
But the Lord determined to bring down that strong
will in me which would have its own way;
so after many days of sore conflict respecting them and the cravat, I was made to submit,
and actually got my wife to make me a supply of the latter article.
I thought to have sold several of the books I once leaned upon,
but I considered I had been deceived by them,
and to prevent their doing further mischief, I cast them into the fire.

Now I looked like a plain Friend; and the first day I put on these clothes,
I was ashamed before my former acquaintance, being mostly among what are called gentry.
I thought I had suffered abundantly for Truth`'s sake,
and that my troubles were almost at an end;
not considering that what had been done already was only the cutting
off of the boughs of that ungodly tree which grew in my heart;
and that the body and root remained, as it were, untouched.
However the Master, who had called me into the vineyard,
knew what work was most befitting me.
About this time I became acquainted with an honest woman Friend,
whom the Lord made instrumental for my help on several occasions,
for which mercy I desire to be thankful.
The first day I put on my clothes, I walked out of town three or four miles,
the Lord raising a cry in my heart, that as I had taken the mark of a holy profession,
I might not, by my life and conduct, bring dishonour thereupon.
Being now out of business, I spent most of my time in going to Meeting,
and walking in the fields retired, where the Lord showed me I was lacking in many things,
concerning plainness of speech, which is the language of Truth; the keeping on of my hat,
and refusing the customary salutations.
These crosses to my natural inclinations brought me under
much exercise many days and nights before I could submit.
But I knew the Lord to be a swift witness against the evil nature that was in me;
and many times, when my hand was on my hat to pull it off, I felt in myself condemned,
so that I dared not do it; so likewise in speech, and such things as, by many,
are accounted little matters.
Yet these troubled me for months,
and many hearty earnest cries did I put up to the Lord for help, which, in His own time,
He was pleased to afford; for which, and all other mercies, I desire to be thankful.

I now began to consider what business I must commence
for the maintenance of myself and my wife.
My capital not exceeding sixty pounds, I feared to enter upon my own trade.^
footnote:[A Confectioner, it is believed.--__Editor__]
In a little while I heard of a Friend who wanted a foreman in that line.
On speaking to him, I found the work was very different to what I had been accustomed,
and I thought it much too mean for me to accept.
I therefore felt unwilling to engage.
Friends were very loving to me in this matter,
and they desired me to make trial of the occupation; which I did,
and discovered that the greatest hindrance to it had been the pride of my own heart.
I was made willing to submit, this being the day of the Lord`'s power.
I made no positive bargain with my employer; he was to give me what he thought I deserved.
After I had been about six months in this situation,
the Lord brought down that lofty domineering masterful spirit,
so that I was made submissive even to the boys of the place,
and willing to do the meanest work, although I had two or three men under me,
and was capable of managing the highest department.
My mistress did not profess with Friends, but was loving towards them.
Therefore I was mindful never to go from business without her permission,
except I went to Meetings; and so particular was I on this point,
that I dared not go home before my usual time, even though I had nothing to do.
And I was as much concerned for the interests of my employer,
as if the business had been my own; which often made me admire the excellence of Truth,
so truly (as kept to) does it teach all of us our duties in every station of life,
and make us a comfort and happiness to each other--a
qualification which is too much lacking in the world.

The Lord showed me that justice was a first lesson of piety;
and by degrees I saw that He required I should practise it,
by paying my creditors what I owed,
notwithstanding they had severally given me a discharge when I relinquished housekeeping.
The sum owing was nearly forty pounds;
and many were the reasonings I had against paying it out of my small stock,
thinking I should be better able at a future day--that doing
so now would leave me penniless and much more of this nature;
so that while I had clearly seen my duty, I had nearly so far neglected it,
as to persuade myself it was not required of me.
So easy is it for men, by carnal reasoning and disobedience,
to lose the sense of conviction,
and then cover themselves by saying they see no harm in this or the other wrong thing.
But in a little time, I began to lack that sweetness, comfort, and satisfaction,
I had inwardly enjoyed, when found in the way of well-doing; and, instead thereof,
trouble was upon me.
But the Lord led me to look into myself, and there to inquire the reason;
when He was pleased to condescend to show me clearly,
it was His will I should pay these creditors at this time;
and for the rest I should trust in Him, casting my care upon His goodness.
In His strength I was enabled to put this into execution.
I got the money out of my wife`'s hands,
and appointed my creditors to meet me at a house, near where the debts were contracted.
There they brought their accounts, and I paid them in full,
by which means I almost emptied my bag.
I told them they might be glad I had become a Quaker, otherwise they had never been paid;
and the Lord gave me much peace in this affair.

The plain language being my present exercise,
an occasion offered for a trial of my faithfulness,
as follows:--A poor man came to ask me if I would
go with him to a parliament man of my acquaintance,
to do him justice in a matter of which I had some knowledge;
and I was willing to serve him, but was under a slavish fear as regarded my appearance.
However I went, crying in my heart for preservation in faithfulness;
and when I knocked at the door, he (who had known me so well) came himself to it;
but the change in my habit and demeanour so surprised him, he scarcely knew me.
I looked simply at him, asking how he was; and after he had expressed his wonder,
he enquired of me my business, which I related; when he would have excused himself.
But I, knowing he had heard how I had served my creditors, boldly told him,
"`justice was a first lesson of piety; that doing justly, loving mercy,
and walking humbly with God, was what no true Christian could omit.`"
At my freedom he seemed astonished, but complied with my request,
calling for wine to make me drink,
and professing his readiness to serve me when occasion required.
Thus we parted.

Having a knowledge of the holiness and purity in the Truth,
I now became a great disputant for it, and for Friends,
thinking all professors thereof were saints;
and when I heard any telling of Friends`' weaknesses, I would defend them violently;
through which I was wounded and full of sorrow,
for having acted more out of the heat of my own spirit,
than from a solid concern to be found acting in the wisdom of Truth.
But the Lord, who knew the sincerity of my intentions, passed it by,
and healed my wounds, teaching me that I was to stand still on such occasions,
and wait for counsel from Him.
I have found it safest to avoid unnecessary disputes; to look well to my own heart,
and not meddle with what was not called for at my hands.
In this quiet waiting on the Lord,
I have found strength to stand wisely for His Truth against opposers; and,
when in the fields and solitary places,
prayers have been raised in my heart for my natural relations,
more especially on behalf of my mother, whom I much desired to see.

My master having but little business, I did not feel freedom to receive his money,
my service becoming no more than what his apprentice could do without me.
I had no other way of getting a penny for my support,
yet in strict justice to him I could not remain.
Hence we parted, and it was nearly seven months before I received a shilling,
during which period I went to see my mother,
in whom I perceived the Lord had begotten an honest concern for her soul`'s salvation.
We had much unity in spirit,
though I met with some close exercise in the town where she lived,
and in which I was born.
I was concerned to visit the steeple-house at the time of public worship,
and to sit down in the place in view of the priest and the people;
and to become as a gazing stock unto them.
I stayed through their services,
letting the people pass and make their observations upon me,
which was a hard thing to endure, and cost me much heart-work;
but the Lord prevailed in making me willing, so that I had peace therein.

I met a kinsman there, who had been born at Oxford,
towards whom I felt a secret drawing in my mind.
After solid consideration,
I had freedom to speak with him on the all-important subject of religion,
having a sense that the Lord was at work in his spirit,
and that he felt a secret love to me.
An epistolary correspondence shortly commenced between us;
and he was so far convinced of the Truth, as to refuse the order of priesthood,
which he intended to take.
He was often visited by the influence of the Spirit,
and his understanding was in some degree opened,
yet he had not strength to give up to the Lord fully,
and to trust in the power of His might.
He was taken ill in London of the small pox, which held him about five days.
He suffered much both in mind and body, and was, I believe, thereby prepared for death.
He acknowledged his unfaithfulness to conviction and manifest duty,
and craved for mercy and forgiveness of the Lord,
and obtained that assurance and hope which makes not ashamed.
This was a great comfort to me, proving to my satisfaction,
that my mental exercises on his account had not been in vain.
This, and many other instances, I have known,
plainly show that God answers the cries of His own begetting
in the hearts of those who love and desire to serve Him.

After returning from my visit to my mother and friends in the country,
I had much peace and satisfaction.
I had not been long in London, however, before the consideration arose,
of "`What must I do to obtain a livelihood?`"
And this became my hourly concern, and great was my trouble respecting it.
My friends and acquaintance began to despise me;
my wife grew uneasy at the prospect before her; and what added to my sorrow was,
that a Friend would be telling her I was an idle lazy fellow,
and acted very unlike the Friends, who were industrious.
He endeavoured to possess her mind with many things of this nature, forgetting,
at the same time, that I could find no business to do.
I used all means possible to obtain employment;
and this usage from a Friend was very hard to bear, almost causing me to stumble;
but the Lord who knew my heart,
and to whom I could make the appeal that I did neither eat the bread of idleness,
nor was I burdensome to any, upheld and gave me patience under the trial.

At this crisis I may truly say that I had no friend to flee to but God alone,
to whom I often retired in secret, pouring out my complaints before Him in the fields,
and in solitary places; many times in those very fields, and in sight of that very house,
where I had formerly committed the greatest excesses,
and wickedly spent my time and my money in very vanity.
Here I was made to mourn with great bitterness and lamentation for my past sinful life.
Oh! how did I bewail my lost time;
and how deep were my cries to the Lord for mercy and preservation,
that I might hold on my way;
for fearful and unbelieving thoughts were often my companions;
and so great was my sorrow, that almost every road, field, and street, I walked in,
were partakers of my tears.
Yet under this my soul heard the voice of rejoicing over one sinner that repents:
and under all, the Everlasting Arms upheld me, so that I delighted in sorrow;
and it was really pleasant, by reason of the hope raised,
that God would work by it for His glory, and my good.
Several months did I so continue, often crying to the Lord for strength to support me;
and when I have prayed Him to make way for me, respecting outward business,
I have been answered, "`Trust in me,
and let patience have her perfect work:`" and deep has been
my travail that I might be enabled so to trust.
Oh! the needs I have seen in myself, when the answer has been,
"`Your God shall supply all your needs.`"
Thus the Lord was pleased to lead me along; and I might say, with one of old,
"`Your rod and your staff they have comforted me;`"--but surely this was a time of love,
and my soul was gained upon, even under sorrow.

I was concerned the Lord might direct even my outward affairs,
that I might have regard to Him for wisdom and counsel,
and fall into such business as would furnish opportunity to wait upon Him,
having seen that it was good to look to him in outward matters,
for by this I should acknowledge His divine providence to overrule.
My reason, which He had given me to govern my outward affairs,
was thereby quickened and cleared; and I found, in matters of importance,
I ought not to be hasty,
but be sure to look well that the proceeding be attended with freedom of spirit,
sincerity of intention, and not for self-ends; ever maintaining a jealousy there.
Thus, when the Lord had tried my faith and patience,
way was made for business according to my desire: and although I have had much exercise,
temptations, and provocations, I have received more than I could have asked.

Notwithstanding many offers that seemed advantageous,
and to which honest Friends advised me,
yet I never had freedom to move from my present settlement;
and I do now believe the Lord, in His kindness, has kept me in it for a good end;
as my removing to a higher station might have hurt me;
for which mercy I desire to be humbly thankful.
In this exercise I learned to get gain in the liberty of the Truth,
and to avoid unlawful gain, wherein is the curse;
and I saw the danger many were in by setting their
minds so much on the things of this life,
as to lose their concern for the hidden Treasure which is everlasting;
and in the eager pursuit thereof, they are brought under many temptations,
by which they "`pierce themselves through with many sorrows.`"
It was here I saw that those who had most of this world`'s good,
had most care upon them to discharge themselves in glorifying God;
and that that treasure left a sting, being often sent for a trial of their fidelity,
under which many fall from their simplicity: all which I was warned against,
and knew that God was not a hard master,--that He required of none
more than He gave ability to perform,--that in what is lent to
man there might be a lawful enjoyment of part in thankfulness,
fear, and freedom of spirit, which is a great mercy and comfort.

And now I may give some account of what I met with from a spirit of deceit and self-righteousness;
so that in reading the text, "`When the Spirit of Truth does come,
it shall convince the world of sin, of righteousness,
and of judgment,`" I have often said, "`I have no righteousness to be convinced of,
so that part I should have nothing to do with;`" but to my great sorrow I found it otherwise.
For having, as I thought, done and suffered much for the Truth,
being measurably preserved from the evils I was formerly guilty of,
and having "`a zeal for God,
but not according to true knowledge,`" I began to think myself very righteous,
even more than many brethren,
from which I took liberty to pass many uncharitable judgments
on those I am now satisfied were much better than myself.
I thought myself good enough to be a preacher, and many times when at meetings,
I have been under a concern, which seemed to spring from the Truth;
such Scriptures opening to my mind as I thought I was to preach.
I could pray in great zeal a long time; and could, I thought, sing the Hebrew song,
but found it afterwards a Babylonish hymn.
When alone, I had fine large openings, which confirmed me I must be a preacher,
thinking I had wit enough to do it better than many; and had not the Lord preserved me,
I had appeared as a minister to my hurt; but he who knew my sincerity,
mercifully made manifest, by degrees, the deceitfulness of this spirit: and,
deepening my experience, He at times led me to the place of true prayer,
and gave me to perceive the mystery of iniquity working in my heart.

The travail of my soul was very great before the Lord,
that I might know this nature in me, and be preserved from its evil workings.
And He was pleased to answer my cry; which mercy, among many others,
I desire never to forget.
Oh! the many years of anguish and deep sorrow of heart I
had to endure before I got the better of it;
and even to this day, if I watch not diligently it will put up its evil head,
and take possession of my thoughts.
Many were the transformations--the subtle operations--the
cunning appearances of this pretended Angel of Light,
and various the bad fruits which were produced in me:--spiritual pride;
zeal without true knowledge; lack of love;
errors in judgment respecting the real state of other vineyards,
to the neglect of my own;
whereby I was in frequent danger of falling into those very temptations
and snares concerning which I so much and so readily condemned others.
If the Lord had not been on my side, working wonders for me, I had been utterly lost.
But in His lovingkindness,
I was shown that these were the delusions of the imagination picturing a sort of likeness,
and sitting as a Lord.--They were sparks of my own kindling,
and my portion was to lie down in sorrow many times.
The Lord showed me there was but _one_ Mediator between God and man, and that was Christ,
__by His Spirit;__--that without Him I could do nothing acceptable to God.
No concern, no zeal, no vows, no prayers, no performances whatsoever, _out of that Spirit,_
had any acceptance with Him.
Those who would bring honour to God, must be subject to His Holy Spirit in all things;
for other spirits would honour Him in _words,_ but in _works_ they deny Him,
taking the glory to themselves.
I have found, by living experience,
that the workings of man`'s spirit are for the exaltation of the creature;
and I know that saying of Christ`'s to be everlastingly true,
namely,--"`He that speaks of himself seeks his own glory;
but he that seeks the glory of Him that sent him, the same is true,
and no unrighteousness is in him.`"

Although the Lord has passed by errors of the kind above named,
when I committed them in ignorance, yet, when I was better taught,
I suffered much more because of my carelessness; but through all,
the Lord preserved that sincerity he had begotten in my heart.
By degrees I learned to fast and to pray,
that I might be enabled to _starve_ that spirit of self in me;
and to accept none of the serpent`'s food, which was but dust;
but to feed on that Bread only which comes down from God out of heaven.
And I was given to see,
that this spirit was of that nature which the disciples could not cast out,
when they asked Christ the reason,
and received for answer,--"`This sort goes not out but by prayer and fasting.`"

When there was great enjoyment in Meetings, I was made to be content to fast,
and feel thankful for the least crumb I could gather from the Holy Table:
I learned to stand still till the Lord had gained
me the victory over all my carnal willings,
runnings, and impatience.
When I sat down in a Meeting,
I was brought in stillness to see the conquering arm of the Lord:
and even then I dared not stir in any exercise till His power went before me,
and cooperated with my spirit.
Many times I had only the office, as it were, of a doorkeeper, which,
when I was careful to discharge with faithfulness, I had the sweet reward of peace.
Here I was taught in the school of Christ to know, that the only work we should perform,
is that in which the Lord employs us; that His is the best and the only accepted time;
and it is always our business to mind the present work and time,
and not to be curious in seeking after more than is fitting for us,
nor covetous of gifts beyond our measure, or in our own wills;
but our coveting should be in His will, opened in the Light.
I also saw that "`The Life is more than food, and the Body,
(which is Christ) than raiment;`" and that we ought to covet faith and hope,
but most of all _love._

But, turning back a little in my narrative;--after times of great trial,
I had seasons of much comfort, when my soul was more enlarged;
and love to God increased in my heart;
then I would be entering into covenant with Him to keep His statutes and his judgments;
and promising, if he would be with me, and be my God, I would, in His time,
follow Him in all His requirings.
I often retired alone into the country,
where the Lord was pleased to open several things
to my understanding respecting my state and condition,
and raise a cry in my heart, to carry on His own work in me; I being willing,
as I thought, that the Lord should do it in His own time, and in His own way; and that,
with assistance, I should be faithful.
But when my request came to be granted,
I found that I neither liked the time nor the way prescribed,
for the root of the tree of iniquity was not yet plucked up,
but remained and grew in my heart; and I had plumed myself into false confidence,
from having, as I believed, had times of encouragement, and that my mountain was strong,
though it lasted only for a season.
Being sincere, a cry was raised in me for _entire deliverance_ from the thraldom of sin,
that without reserve there might not be anything
left alive which was offensive in the Divine sight;
and that all my affections might be weaned from the things of death.

And now the axe was laid to the root of the ungodly tree,
sin revived various temptations within me to many old evils;
and provocations of various sorts were raised up against me--in short,
the old nature was all in a ferment in my soul.
These were seasons of deep sorrow, humiliation, and trial;
and I was made to witness the state spoken of by the apostle, when he says,
"`I see another law in my members, warring against the law of my mind.`"
For I did many things to which my mind consented not; and yet, under this great trouble,
the Lord`'s arm of power lifted me up.
Many and fervent were my cries for deliverance from this body of sin and death;
but I could not get from under it in my own way and time,
because _that_ in me which had joined issue against the Lord,
must partake of the plagues He was now pouring on
that spirit that would rule in my heart,
and by which the holy name of the Lord was blasphemed.
I saw that iniquity only endured for a season, but that Truth endures forever;
that if Satan did his worst, still the Lord would get Himself honour;
and that I should trust in the Lord, wait His time, and keep the word of His patience.

Thus was I brought to be resigned to the will of God; and to say in my heart,
"`The Lord is wiser than man; it is His quarrel,
and on Him will I wait until He has gained the victory for me.`"
In my heart the battle was carried on, which was no small pain to the flesh,
the Lord kindling the fire of His judgments against Satan,
who used all power to keep his habitation.
The Lord, by the sword of his eternal word, cut off many things my soul had been,
as it were, glued to.
The famine began in the land, for starving that frothy wisdom I so much gloried in.
The pestilence of His fury was poured on the first nature in me;
and many were the slain of the Lord in that day.
I loved His judgments, and was willing He should cut open my heart,
and let out all the blood which had given life to those things that offended Him.
This was heart-work indeed--it was deep searching of heart,
and my body was affected by it.
Many times I wished for death rather than life.
My countenance grew pale, and I often laid my hands on my loins,
being in great pain from days of sorrow and nights of trouble,
in consequence of the separation the Lord made between my
soul and that wicked spirit to which it had been joined.
Thus he led me on; and in due time He healed my wounds,
and bid me be valiant and follow Him, promising that I should gain the victory at last.

And now I can say, "`a man`'s enemies are those of his own house;`" for,
notwithstanding the many provocations and temptations which attended me,
had not the evil roots remained, the trouble would have been very little,
because there would have been no inclination to them;
the Lord at times permitting me to see that where He had taken away the inclination,
there the temptation had no force.
Fearful and unbelieving thoughts were often my companions,
and many were my complaints of my troubles to the Lord,
I being quite weary of this great burden;
but I learned that it was the spirit that would save itself which worked those things,
and that I must allow it to be brought forth to the slaughter.
I saw therein the justice of the Holy One;
that body and spirit should be made partakers of the sufferings,
by reason they had been partakers of the sins.
From several causes and persons, I met with many provoking circumstances,
which sometimes made me complain;
but then I remembered what I had formerly done to
others (times and places being brought to mind),
so the measure I had administered, was now administered to me in return.
Thus was I quieted, and made to submit, though long under such kind of errors,
by reason of manifold roots, which were deep in the earth.

Many were my exercises, until the Lord measurably gave the victory;
and as my enemies grew weaker, my faith grew stronger.
Amidst this trouble, I was not without my intermitting seasons of peace and comfort,
enjoying freedom of spirit; and often enlarged in my heart to cry unto the Lord,
that His work might be carried on in others;
but more especially those who were under the profession of Truth,
of which the faithful were near and dear unto me.
Thus, all things worked together for good; hope increased in my mind;
and I became more in love with the Lord and His ways;
and many opportunities I had of doing some small services, in which I was willing,
but found something in myself to oppose when I saw
the line of my duty to be in the cross.
So I felt I had need of strength from God to perform
the smallest matter relating to services;
my chief desire being to set forth the love of God to mankind.

I shall now return to give further account of my friend,
who came to London about six or seven weeks after me;
having continued in a course of drunkenness most of that time,
and unhappily fallen in with his associates in wickedness in London,
so that for some weeks, though I endeavoured, I could not find him.
At length I accidentally met him in the street,
and his very outward appearance discovered his inward man.
He could scarcely speak without swearing--a practice to which he was not formerly addicted.
In short he was the very reverse of anything that looked like good.
Notwithstanding it was so with him, I loved him,
and am satisfied my love proceeded from the love of God in my heart; so true it is,
that Christ loved us when we were yet sinners and enemies to Him;
and his love was extended towards my friend.
But I was concerned to see him so bad,
and could not part with him till we went to a house together.
After being with each other awhile,
he gave me an account of his proceedings since we parted,
which brought inexpressible sorrow on my spirit; but I had relief,
in that the Lord followed him with judgments,
bringing him to town against his inclination; for the terrors of the Lord so pursued him,
that he dared not stay any longer in the country.
I used endeavours to persuade him to forsake his companions, and to go to Meeting,
that he might gain strength--but in vain; he dared not yet go to Meetings,
as his friends in town were intent on diverting him from his intention of being a Quaker;
so that all manner of instruments and opportunities were devised for this purpose;
and his being wholly at liberty, in full pocket, etc.,
helped to keep him in bondage to his old master,
yet the Lord still mercifully followed him.

When under judgments and terrors, he would come and tell me how things were.
Hence I was much concerned for him;
and sometimes I took him out of the way into the country; sometimes got him to Meeting,
where I was desirous that the Lord would open something
in his servants that might be serviceable to him.
I had my prayer answered by a Friend speaking directly to his state,
so that it affected him, and he began to think of being obedient;
but then he would run back again, and had many afflictions,
with signs and wonders from the Lord upon Pharaoh`'s nature in him;
still that hard task-master would not let him go to serve his God.
He came and told me that, if he did not give up in obedience,
he believed the Lord would cut him off; which so affected him,
that he began to go to Meetings;
and the Lord was pleased to afford him strength to come up in obedience,
and confess Christ before men--causing him to grow in the Truth.
But the enemies did not fail to pursue, and many battles they had;
yet the Lord hitherto in mercy kept him,
giving him more than ever he could expect in this world--goods,
and a wife to his mind--as I am a witness for God,
of His great kindness to him every way.

And now I desire for him, and all the visited of the Lord,
that we may be preserved in His fear, never forgetting His mercy,
and especially his lovingkindness, for I cannot but say our visitation has been large.
If we should serve idols of our own making, and love anything better than Him,
I will acknowledge we deserve double punishment.
And I do believe it will be more tolerable in the
judgment for the worst of men than for us,
should we go back again into Egypt, and thus miss of obtaining the good land.

[.asterism]
'''

Here ends the manuscript of our deceased Friend,
whom the Lord was pleased to visit in His great love and tender mercy,
and to bring into favour with Himself, after having been long in rebellion,
under hard bondage, and great slavery to sin and Satan.
Under these strivings of a Saviour`'s love,
he was brought to see the vanity and uncertainty of all things
here below--to fix his heart on those which are enduring,
and steadily pursue the things which make for peace, even to the end.
In perusing such gracious dealing and blessed experience thus wrought out,
and seeing how strength was afforded to come out of the miry clay,
in which his feet had been so deeply entangled,
how are we led to admire and adore that condescending goodness
which followed him and his friend year after year,
until its purpose was effected!
And how are we invited to come unto Him, who can save to the very uttermost,
in every exigency, and from all iniquity; and will not cast out any who sincerely repent,
while pardoning mercy is offered!
Very strikingly is this exhibited by the foregoing pages,
when iniquity was added to iniquity,
until the measure thereof was believed to be nearly
filled;--nearly approaching that awful crisis,
when the things of peace are forever hid,
and there remains "`no place for repentance,`" no "`sacrifice for sins.`"
(See Heb. 10:26,
and 12:17.) But in observing herein the "`brand plucked
from the burning,`" the net of destruction broken,
and an escape provided,
how are we animated to forsake all ungodliness,--to lay aside every weight, and pursue,
in the Divine fear, the same hope set before us,
so that we may "`die the death of the righteous, and our latter end be like his!`"

N+++.+++ B.--As John Davis`'s account of himself and his
friend concludes with some deficiency of information,
it may not be amiss to supply the best we can,
by subjoining the testimony his surviving friends gave of him,
as prefixed to the original copy in MS.:--

[.embedded-content-document.testimony]
--

The following pages are the memoir of our worthy friend John Davis, late of London, who,
we believe, through various trials, and much experience,
gained an establishment in the blessed Truth.

He was esteemed a valuable Elder in the Church; lived, beloved by his friends,
to a good old age; and was gathered to rest as a shock of corn fully ripe.

He died at Winchmore Hill, and was buried in Friends`' burial ground there,
in or near the Fourth Month, in the year 1744, aged about seventy-seven years.

--

[.the-end]
The End
